import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import SideHeader from "./_components/SideHeader";

const cairoFont = Cairo({
  variable: "--font-cairo-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="ar" dir="rtl">
  <body className={`${cairoFont.variable} antialiased flex`}>
    <SideHeader />
    <main className="flex-1 mr-[265px]"> 
      {children}
    </main>
  </body>
</html>


  );
}
